name: Documentation
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.x
      - name: Generate cache id
        id: cache-id
        run: |
          echo "cache-id=$(date --utc '+%V')" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache@v3.3.1
        id: cache
        with:
          key: data-driver-docs-${{ steps.cache-id.outputs.cache-id }}
          path: .cache
          restore-keys: |
            data-driver-docs-
      - name: Install dependencies
        run: |
          sudo apt install pngquant
        shell: bash
      - name: Install Python dependencies
        run: |
          pip install mkdocs-material
        shell: bash
      - name: Build
        run: |
          mkdocs build
        shell: bash
      - uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: ./site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: docs
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v2.0.3
        id: deploy